{"uuid": "51ab6a0e-f229-46c6-9b3f-58f3e8e613e5", "children": ["9ca60656-ff91-4dd9-8ed8-3f13df694d15"], "befores": [{"name": "random_user", "status": "failed", "statusDetails": {"message": "AssertionError: Failed to register user. Response: {'success': False, 'message': 'User already exists'}\nassert 403 == 200\n +  where 403 = <Response [403]>.status_code\n", "trace": "  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\_pytest\\fixtures.py\", line 895, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Leila Magomedova.WKST-QA-08\\PycharmProjects\\Diploma\\Diplom_3\\conftest.py\", line 34, in random_user\n    assert response.status_code == 200, f\"Failed to register user. Response: {response.json()}\"\n"}, "start": 1715533449882, "stop": 1715533450508}], "start": 1715533449882, "stop": 1715533450514}